modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

displayURL="https://github.com/xy2407/XY2407-NSUK-Addition"

authors="xingying2407"

description='''
XY2407 NSUK Addition - Extension mod for New:Sim-U-Kraft.
Fish breeding, ore vein mining, auto restock & store, city building expansion, and more.
'''

[[mixins]]
config="mixins.${mod_id}.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simukraft"
    type="required"
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="letfishlove"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tide"
    type="optional"
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="aquaculture"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="vinery"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kaleidoscope_tavern"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="CLIENT"